version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "peng"
s3_bucket = "peng-data"
s3_prefix = "peng"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
