AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Prefix:
    Type: String
    Default: peng
  BookCoverBucketName:
    Type: String
    Default: book-covers
Resources:
  BookCover:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-data/569d609c9571c4dd9753fec457f6a46f
      Runtime: nodejs16.x
      Handler: app.handler
      Events:
        UploadBookCover:
          Type: S3
          Properties:
            Bucket:
              Ref: BookCoverBucket
            Events: s3:ObjectCreated:*
    Metadata:
      SamResourceId: BookCover
  BookCoverBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${Prefix}-${BookCoverBucketName}-0000
    Metadata:
      SamResourceId: BookCoverBucket
  BookTable:
    Type: AWS::Serverless::SimpleTable
    Metadata:
      SamResourceId: BookTable
  Books:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-data/5ee3c95f0ee9fdaf5a599ae0b36ba224
      Handler: app.handler
      Runtime: nodejs16.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: BookTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        AddBook:
          Type: Api
          Properties:
            Path: /books
            Method: post
        ListBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
        Book:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: any
    Metadata:
      SamResourceId: Books
Globals:
  Api:
    Cors:
      AllowOrigin: '''*'''
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
