AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 10
    MemorySize: 512
  Api:
    Cors:
      AllowOrigin: '''*'''
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
Resources:
  MyS3Api:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-api
      StageName: Test
      Cors:
        AllowOrigin: '''*'''
        AllowMethods: '''*'''
        AllowHeaders: '''*'''
      BinaryMediaTypes:
      - '*/*'
    Metadata:
      SamResourceId: MyS3Api
  JpgBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-jpg
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Metadata:
      SamResourceId: JpgBucket
  JpgApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-proto-package/39bbe8652b55b9c7ecad757d160eed70
      Handler: app.handler
      Runtime: nodejs16.x
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: JpgBucket
      Policies: AmazonS3FullAccess
      Events:
        GetJpg:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /jpg-archive/{id}
            Method: any
        GetRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /jpg-archive/
            Method: get
        PostRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /jpg-archive/
            Method: post
    Metadata:
      SamResourceId: JpgApi
  CsvBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-csv
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Metadata:
      SamResourceId: CsvBucket
  CsvApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-proto-package/79647473cd78436f897c76fbd1053af6
      Handler: app.handler
      Runtime: nodejs16.x
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: CsvBucket
      Policies: AmazonS3FullAccess
      Events:
        GetCsvItem:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /csv-archive/{id}
            Method: any
        GetCsvRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /csv-archive/
            Method: get
        PostCsvRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /csv-archive/
            Method: post
    Metadata:
      SamResourceId: CsvApi
  PrivacyCsvAccessPoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/peng-proto-package/65f19d666ed0d5a0146d60ae8e995dbb.template
      Parameters:
        S3BucketName:
          Ref: CsvBucket
        Interceptors: '["CovidResearchCSVInterceptor", "StatisticsCSVInterceptor",
          "MinistryOfHealthCSVInterceptor"]'
    Metadata:
      SamResourceId: PrivacyCsvAccessPoint
  PrivacyJpgAccessPoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/peng-proto-package/65f19d666ed0d5a0146d60ae8e995dbb.template
      Parameters:
        S3BucketName:
          Ref: JpgBucket
        Interceptors: '["TUCancerResearchJPGInterceptor", "ResearchJPGInterceptor",
          "NoMetadataJPGInterceptor"]'
    Metadata:
      SamResourceId: PrivacyJpgAccessPoint
Outputs:
  '0NormalJpgRestApi':
    Description: Severless normal REST api for jpg files
    Value:
      Fn::Sub: https://${MyS3Api}.execute-api.${AWS::Region}.amazonaws.com/Test/jpg-archive/
  '0PrivacyConformJpgApi':
    Description: Severless privacy conform api for jpg files
    Value:
      Fn::GetAtt:
      - PrivacyJpgAccessPoint
      - Outputs.PrivacyAccessApi
  1NormalCsvRestApi:
    Description: Severless REST api for csv data
    Value:
      Fn::Sub: https://${MyS3Api}.execute-api.${AWS::Region}.amazonaws.com/Test/csv-archive/
  1PrivacyConformCsvApi:
    Description: Severless privacy conform api for csv files
    Value:
      Fn::GetAtt:
      - PrivacyCsvAccessPoint
      - Outputs.PrivacyAccessApi
