AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 10
    MemorySize: 512
Resources:
  PhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-data
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Metadata:
      SamResourceId: PhotoBucket
  MyS3Api:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-temp
      StageName: Test
      BinaryMediaTypes:
      - '*/*'
    Metadata:
      SamResourceId: MyS3Api
  RestApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-proto-package/af011f7319763c364060aedcd67287f8
      Handler: app.handler
      Runtime: nodejs16.x
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: PhotoBucket
      Policies: AmazonS3FullAccess
      Events:
        GetHealthphoto:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /healthphotos/{id}
            Method: any
        GetRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /healthphotos/
            Method: get
        PostRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyS3Api
            Path: /healthphotos/
            Method: post
    Metadata:
      SamResourceId: RestApi
  PatientTable:
    Type: AWS::Serverless::SimpleTable
    Metadata:
      SamResourceId: PatientTable
  Patient:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-proto-package/4d6d878600370a7fdc9f7a8f2a2ca029
      Handler: app.handler
      Runtime: nodejs16.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: PatientTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        AddPatient:
          Type: Api
          Properties:
            Path: /patients
            Method: post
            RestApiId:
              Ref: MyS3Api
        ListPatient:
          Type: Api
          Properties:
            Path: /patients
            Method: get
            RestApiId:
              Ref: MyS3Api
        Patient:
          Type: Api
          Properties:
            Path: /patients/{id}
            Method: any
            RestApiId:
              Ref: MyS3Api
    Metadata:
      SamResourceId: Patient
Outputs:
  HealthPhotoRestApiUrl:
    Description: Severless REST api for health photos
    Value:
      Fn::Sub: https://${MyS3Api}.execute-api.${AWS::Region}.amazonaws.com/Test/healthphotos/
  PatientRestApiUrl:
    Description: Severless REST api for patient data
    Value:
      Fn::Sub: https://${MyS3Api}.execute-api.${AWS::Region}.amazonaws.com/Test/patients/
