version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "peng"
s3_bucket = "peng-proto-package"
region = "eu-central-1"
confirm_changeset = true
disable_rollback = true
image_repositories = []
