AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  deploymentEnvironment:
    Type: String
    Default: test
Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 10
    MemorySize: 512
Resources:
  Authenticator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-runtime/8063ad911ba6ddd86a5c15c70413d964
      Handler: authenticator.handler
    Metadata:
      SamResourceId: Authenticator
  AuthGateway:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/gif
      - image/x-icon
      - application/octet-stream
      StageName:
        Ref: deploymentEnvironment
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn:
              Fn::GetAtt:
              - Authenticator
              - Arn
            Identity:
              ReauthorizeEvery: 0
              QueryStrings:
              - accessToken
    Metadata:
      SamResourceId: AuthGateway
  GetObject:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-runtime/8063ad911ba6ddd86a5c15c70413d964
      Handler: get-object.handler
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: MyS3Bucket
          S3_ACCESS_POINT:
            Fn::GetAtt:
            - MyS3ObjectLambdaAccessPoint
            - Arn
      Policies:
      - AmazonS3FullAccess
      - AWSLambda_FullAccess
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: AuthGateway
            Path: /objects/{id}
            Method: get
    Metadata:
      SamResourceId: GetObject
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-data
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    Metadata:
      SamResourceId: MyS3Bucket
  MyS3ObjectLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://peng-runtime/8063ad911ba6ddd86a5c15c70413d964
      Handler: anonymizer.handler
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: MyS3Bucket
      - Statement:
        - Effect: Allow
          Action: s3-object-lambda:WriteGetObjectResponse
          Resource: '*'
    Metadata:
      SamResourceId: MyS3ObjectLambda
  MyS3AccessPoint:
    Type: AWS::S3::AccessPoint
    Properties:
      Bucket:
        Ref: MyS3Bucket
      Name:
        Fn::Sub: ${AWS::StackName}-support
    Metadata:
      SamResourceId: MyS3AccessPoint
  MyS3ObjectLambdaAccessPoint:
    Type: AWS::S3ObjectLambda::AccessPoint
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-anon
      ObjectLambdaConfiguration:
        SupportingAccessPoint:
          Fn::Sub: arn:aws:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/${MyS3AccessPoint}
        TransformationConfigurations:
        - Actions:
          - GetObject
          ContentTransformation:
            AwsLambda:
              FunctionArn:
                Fn::GetAtt:
                - MyS3ObjectLambda
                - Arn
              FunctionPayload: test-payload
    Metadata:
      SamResourceId: MyS3ObjectLambdaAccessPoint
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Hello World function
    Value:
      Fn::Sub: https://${AuthGateway}.execute-api.${AWS::Region}.amazonaws.com/${deploymentEnvironment}/objects/test.png?accessToken=testabc
