AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  deploymentEnvironment:
    Type: String
    Default: "test"
  S3BucketName:
    Type: String
    Default: "peng-test-data"

Globals:
  Function:
    Timeout: 300
    MemorySize: 1024

Resources:
  # PrivacyInterceptor
  PrivacyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Runtime: nodejs16.x
      Handler: privacy-lambda.handler
      Policies:
        - AmazonS3FullAccess

  # S3 Access Point (Network origin: Internet)
  SupportAccessPoint:
    Type: 'AWS::S3::AccessPoint'
    Properties:
      Bucket: !Ref S3BucketName
      Name: !Sub "${S3BucketName}-support"

  PrivacyS3ObjectLambdaAccessPoint:
    Type: 'AWS::S3ObjectLambda::AccessPoint'
    Properties: 
      Name:  !Sub "${S3BucketName}-privacy"
      ObjectLambdaConfiguration:
        SupportingAccessPoint: !Sub 'arn:aws:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/${SupportAccessPoint}'
        TransformationConfigurations: 
        - Actions:
            - GetObject
          ContentTransformation: 
            AwsLambda:
              FunctionArn: !GetAtt PrivacyLambda.Arn

  # Access S3 Object Lambda Microservice
  GetS3ObjectApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${S3BucketName}-anonAccess"
      BinaryMediaTypes:
        - '*/*'
      StageName: !Ref deploymentEnvironment

  GetS3ObjectLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Runtime: python3.8
      Handler: get-object.lambda_handler
      Environment:
        Variables:
          S3_ACCESS_POINT: !GetAtt PrivacyS3ObjectLambdaAccessPoint.Arn
      Policies:
        - AmazonS3FullAccess
        - AWSLambda_FullAccess
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref GetS3ObjectApi
            Path: "/anonymize-object/{id}"
            Method: get

Outputs:
  PrivacyAccessApi:
    Description: "Privacy Access Endpoint Url"
    Value: !Sub "https://${GetS3ObjectApi}.execute-api.${AWS::Region}.amazonaws.com/${deploymentEnvironment}/anonymize-object/"