AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Prefix:
    Type: String
    Default: peng
  BookPicturesBucketName:
    Type: String
    Default: book-s3
Resources:
  BookPicturesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${Prefix}-${BookPicturesBucketName}-0004
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    Metadata:
      SamResourceId: BookPicturesBucket
  S3ProxyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name:
        Ref: AWS::StackName
      BinaryMediaTypes:
      - '*/*'
    Metadata:
      SamResourceId: S3ProxyApi
  S3Proxy:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: ANY
        IntegrationResponses:
        - StatusCode: 200
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:s3:path/${BookPicturesBucket}
        Credentials:
          Fn::GetAtt:
          - AllowAccessRole
          - Arn
      ResourceId:
        Fn::GetAtt:
        - S3ProxyApi
        - RootResourceId
      RestApiId:
        Ref: S3ProxyApi
    Metadata:
      SamResourceId: S3Proxy
  AllowAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: AllowAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: '*'
            Effect: Allow
            Resource:
            - Fn::GetAtt:
              - BookPicturesBucket
              - Arn
    Metadata:
      SamResourceId: AllowAccessRole
